name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12  # Specify the Python version if needed
        auto-update-conda: true  # Update to the latest version of Conda
        activate-environment: my-env  # Name of the environment you want to create
        #environment-file: environment.yml

    - name: Install Conda Dependencies
      run: |
        conda create --name my-env python=3.8 -y       
        conda activate my-env
        conda install -c conda-forge openmm -y
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./docs/requirements.txt
    
    - name: Install pandoc
      run: sudo apt-get install -y pandoc
      
    - name: Run tests or build documentation
      run: |
        conda activate my-env
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html

      # - name: Set up Python
      # uses: actions/setup-python@v4
      # with:
      #   python-version: '3.12'  

      # - name: Build Sphinx documentation
      # run: |
      #   cd docs
      #   make html